---
title: "R Notebook"
output: html_notebook
---

This document will assess the level of missing data in some key variables to inform decisions around what data to use, and what needs to be imputed. 

```{r "setup", include=FALSE}

require(haven)
require(mice)
require(lattice)
require(tidyverse)
require(Hmisc)

FEM_dir <- "/home/luke/Documents/E_FEM_clean/E_FEM/input_data/"
knitr::opts_knit$set(root.dir = FEM_dir)

set.seed(500) # Set seed for reproducibility

```

Read in the data.

```{r}

# Read in the data.
H_ELSA_base <- read_dta('H_ELSA_f_2002-2016.dta')

```

Now declare the function to assess the level of missing data.

```{r}

# Calculate percentage of missing cases
pMiss <- function(x) {sum(is.na(x)) / length(x) * 100}

```

Now select key variables from ELSA and apply the function to assess missingness.

```{r}

# Cancer
cancre <- H_ELSA_base %>% select(matches('r[0-9]cancre$'))
apply(cancre, 2, pMiss)
print(' ')

# Diabetes
diabe <- H_ELSA_base %>% select(matches('r[0-9]diabe$'))
apply(diabe, 2, pMiss)
print(' ')

# Lung Disease
lunge <- H_ELSA_base %>% select(matches('r[0-9]lunge$'))
apply(lunge, 2, pMiss)
print(' ')

# smoken and smokev and smokef
smoken <- H_ELSA_base %>% select(matches('r[0-9]smoken$'))
apply(smoken, 2, pMiss)
print(' ')
smokev <- H_ELSA_base %>% select(matches('r[0-9]smokev$'))
apply(smokev, 2, pMiss)
print(' ')
smokef <- H_ELSA_base %>% select(matches('r[0-9]smokef$'))
apply(smokef, 2, pMiss)
print(' ')

# drink
drink <- H_ELSA_base %>% select(matches('r[0-9]drink$'))
apply(drink, 2, pMiss)
print(' ')

rm(cancre, diabe, lunge, smoken, smokev, smokef, drink)

```


```{r}

# Now get the proportion of missing data in variables in raw stock file
stock <- read_dta('ELSA_stock_preImpute.dta')

```


```{r}

pMiss(stock$age)
pMiss(stock$male)
pMiss(stock$bmi)
pMiss(stock$logbmi)
pMiss(stock$smoken)
pMiss(stock$smokev)
pMiss(stock$educ)

print('-----------')

pMiss(stock$cancre)
pMiss(stock$diabe)
pMiss(stock$hearte)
pMiss(stock$stroke)
pMiss(stock$lunge)
pMiss(stock$hibpe)

```
























