---
title: "Burden of Risk Behaviours"
output: html_notebook
---



```{r "setup", include=FALSE}
# Need to set up the environment
workingDir <- "/home/luke/Documents/E_FEM_clean/E_FEM"
knitr::opts_knit$set(root.dir = workingDir)

require(haven)
require(dplyr)
require(ggplot2)
```


# Baseline Plots (Cohort)

```{r}

cohort <- read_dta('output/ELSA_cohort/ELSA_cohort_summary.dta')

# Generate age var
cohort$age <- (cohort$year - 2012) + 50

# Survival curve
cohort$survival <- cohort$m_endpop_all / cohort$m_endpop_all[1]

# Now plot all survival curves together
ggplot(cohort, aes(x=age, y=survival)) +
        geom_line(col='black', size=0.3) +
        labs(title='Cohort Survival Over Time', y='Survival', x='Age')
# Smoking variables and chronic diseases
ggplot(cohort, aes(x=age, y=n_smoke_stop_all)) +
        geom_line(col='black', size=0.3) +
        labs(title='Smoke Stop', y='# Stopped Smoking', x='Age')
ggplot(cohort, aes(x=age, y=p_smoken_all)) +
        geom_line(col='black', size=0.3) +
        labs(title='Prevalence of Smoking by Age', y='Prevalence of Smoking', x='Age')
ggplot(cohort, aes(x=age, y=p_lunge_all)) +
        geom_line(col='black', size=0.3) +
        labs(title='Prevalence of Lung Disease by Age', y='Prevalence of Lung Disease', x='Age')
ggplot(cohort, aes(x=age, y=p_cancre_all)) +
        geom_line(col='black', size=0.3) +
        labs(title='Prevalence of Cancer by Age', y='Prevalence of Cancer', x='Age')

```


# No Smoking Scenario (Cohort)

```{r}

# Read in all the data
cohort <- read_dta('output/ELSA_cohort/ELSA_cohort_summary.dta')
no_smoke_C <- read_dta('output/CureSmoken_C/CureSmoken_C_summary.dta')

# Generate age var
cohort$age <- (cohort$year - 2012) + 50
no_smoke_C$age <- (cohort$year - 2012) + 50

# Survival curve
cohort$survival <- cohort$m_endpop_all / cohort$m_endpop_all[1]
no_smoke_C$survival <- no_smoke_C$m_endpop_all / no_smoke_C$m_endpop_all[1]

# Now plot all survival curves together
ggplot(cohort, aes(x=age, y=survival)) +
        geom_line(col='black', size=0.3) +
        geom_line(data=no_smoke_C, size=0.3, col='green') +
        labs(title='Cohort Survival Over Time', y='Survival', x='Age')
# Smoking variables and chronic diseases
ggplot(cohort, aes(x=age, y=n_smoke_stop_all)) +
        geom_line(col='black', size=0.3) +
        geom_line(data=no_smoke_C, size=0.3, col='green') +
        labs(title='Smoke Stop', y='# Stopped Smoking', x='Age')
ggplot(cohort, aes(x=age, y=p_smoken_all)) +
        geom_line(col='black', size=0.3) +
        geom_line(data=no_smoke_C, size=0.3, col='green') +
        labs(title='Prevalence of Smoking by Age', y='Prevalence of Smoking', x='Age')
ggplot(cohort, aes(x=age, y=p_lunge_all)) +
        geom_line(col='black', size=0.3) +
        geom_line(data=no_smoke_C, size=0.3, col='green') +
        labs(title='Prevalence of Lung Disease by Age', y='Prevalence of Lung Disease', x='Age')
ggplot(cohort, aes(x=age, y=p_cancre_all)) +
        geom_line(col='black', size=0.3) +
        geom_line(data=no_smoke_C, size=0.3, col='green') +
        labs(title='Prevalence of Cancer by Age', y='Prevalence of Cancer', x='Age')

```

# SmokeStopFull (cohort)

```{r}

# Read in all the data
cohort <- read_dta('output/ELSA_cohort/ELSA_cohort_summary.dta')
SSF_C <- read_dta('output/SmokeStopFull_C/SmokeStopFull_C_summary.dta')

# Generate age var
cohort$age <- (cohort$year - 2012) + 50
SSF_C$age <- (cohort$year - 2012) + 50

# Survival curve
cohort$survival <- cohort$m_endpop_all / cohort$m_endpop_all[1]
SSF_C$survival <- SSF_C$m_endpop_all / SSF_C$m_endpop_all[1]

# Now plot all survival curves together
ggplot(cohort, aes(x=age, y=survival)) +
        geom_line(col='black', size=0.3) +
        geom_line(data=SSF_C, size=0.3, col='green') +
        labs(title='Cohort Survival Over Time', y='Survival', x='Age')
# Smoking variables and chronic diseases
ggplot(cohort, aes(x=age, y=n_smoke_stop_all)) +
        geom_line(col='black', size=0.3) +
        geom_line(data=SSF_C, size=0.3, col='green') +
        labs(title='Smoke Stop', y='# Stopped Smoking', x='Age')
ggplot(cohort, aes(x=age, y=p_smoken_all)) +
        geom_line(col='black', size=0.3) +
        geom_line(data=SSF_C, size=0.3, col='green') +
        labs(title='Prevalence of Smoking by Age', y='Prevalence of Smoking', x='Age')
ggplot(cohort, aes(x=age, y=p_lunge_all)) +
        geom_line(col='black', size=0.3) +
        geom_line(data=SSF_C, size=0.3, col='green') +
        labs(title='Prevalence of Lung Disease by Age', y='Prevalence of Lung Disease', x='Age')
ggplot(cohort, aes(x=age, y=p_cancre_all)) +
        geom_line(col='black', size=0.3) +
        geom_line(data=SSF_C, size=0.3, col='green') +
        labs(title='Prevalence of Cancer by Age', y='Prevalence of Cancer', x='Age')


```



# No Smoking Scenario (Population)

```{r}

# Read in all the data
pop <- read_dta('output/ELSA_Baseline/ELSA_Baseline_summary.dta')
no_smoke_P <- read_dta('output/CureSmoken_P/CureSmoken_P_summary.dta')

# Plot Average age at death
ggplot(pop, aes(x=year, y=d_age_all)) +
        geom_line(col='black', size=0.3) +
        geom_line(data=no_smoke_P, size=0.3, col='green') +
        labs(title='Average Age at Death over Time', y='Average age at death', x='Year')
        
# Smoking variables and chronic diseases
ggplot(pop, aes(x=year, y=n_smoke_stop_all)) +
        geom_line(col='black', size=0.3) +
        geom_line(data=no_smoke_P, size=0.3, col='green') +
        labs(title='Smoke Stop', y='# Stopped Smoking', x='Year')
ggplot(pop, aes(x=year, y=p_smoken_all)) +
        geom_line(col='black', size=0.3) +
        geom_line(data=no_smoke_P, size=0.3, col='green') +
        labs(title='Prevalence of Smoking over Time', y='Prevalence of Smoking', x='Year')
ggplot(pop, aes(x=year, y=p_lunge_all)) +
        geom_line(col='black', size=0.3) +
        geom_line(data=no_smoke_P, size=0.3, col='green') +
        labs(title='Prevalence of Lung Disease over Time', y='Prevalence of Lung Disease', x='Year')
ggplot(pop, aes(x=year, y=p_cancre_all)) +
        geom_line(col='black', size=0.3) +
        geom_line(data=no_smoke_P, size=0.3, col='green') +
        labs(title='Prevalence of Cancer over Time', y='Prevalence of Cancer', x='Year')

```



# SmokeStopFull (Population)

```{r}

# Read in all the data
pop <- read_dta('output/ELSA_Baseline/ELSA_Baseline_summary.dta')
SSF_P <- read_dta('output/SmokeStopFull_P/SmokeStopFull_P_summary.dta')

# Plot Average age at death
ggplot(pop, aes(x=year, y=d_age_all)) +
        geom_line(col='black', size=0.3) +
        geom_line(data=SSF_P, size=0.3, col='green') +
        labs(title='Average Age at Death over Time', y='Average age at death', x='Year')
        
# Smoking variables and chronic diseases
ggplot(pop, aes(x=year, y=n_smoke_stop_all)) +
        geom_line(col='black', size=0.3) +
        geom_line(data=SSF_P, size=0.3, col='green') +
        labs(title='Smoke Stop', y='# Stopped Smoking', x='Year')
ggplot(pop, aes(x=year, y=p_smoken_all)) +
        geom_line(col='black', size=0.3) +
        geom_line(data=SSF_P, size=0.3, col='green') +
        labs(title='Prevalence of Smoking over Time', y='Prevalence of Smoking', x='Year')
ggplot(pop, aes(x=year, y=p_lunge_all)) +
        geom_line(col='black', size=0.3) +
        geom_line(data=SSF_P, size=0.3, col='green') +
        labs(title='Prevalence of Lung Disease over Time', y='Prevalence of Lung Disease', x='Year')
ggplot(pop, aes(x=year, y=p_cancre_all)) +
        geom_line(col='black', size=0.3) +
        geom_line(data=SSF_P, size=0.3, col='green') +
        labs(title='Prevalence of Cancer over Time', y='Prevalence of Cancer', x='Year')

```
