---
title: "R Notebook"
output: html_notebook
---


```{r "setup", include=FALSE}
# Need to set up the environment
workingDir <- "/home/luke/Documents/E_FEM_clean/E_FEM"
knitr::opts_knit$set(root.dir = workingDir)

require(haven)
require(dplyr)
require(tidyr)
require(ggplot2)
```


```{r}

pop <- read_dta('output/ELSA_Baseline/ELSA_Baseline_summary.dta')
diabe10 <- read_dta('output/ELSA_pDiabe10/ELSA_pDiabe10_summary.dta')
diabe50 <- read_dta('output/ELSA_pDiabe50/ELSA_pDiabe50_summary.dta')
diabe100 <- read_dta('output/ELSA_pDiabe100/ELSA_pDiabe100_summary.dta')


# Plot Average age at death
ggplot(pop, aes(x=year, y=d_age_all)) +
        geom_line(col='black', size=0.3) +
        #geom_smooth(method="auto", se=FALSE, fullrange=FALSE, level=0.95) +
        geom_line(data=diabe10, size=0.3, col='blue') +
        geom_line(data=diabe50, size=0.3, col='red') +
        geom_line(data=diabe100, size=0.3, col='dark green') +
        labs(title='Average Age at Death', y='Age', x='Year')
        
# Smoking variables and chronic diseases
ggplot(pop, aes(x=year, y=p_diabe_all)) +
        geom_line(col='black', size=0.3) +
        geom_line(data=diabe10, size=0.3, col='blue') +
        geom_line(data=diabe50, size=0.3, col='red') +
        geom_line(data=diabe100, size=0.3, col='dark green') +
        labs(title='Diabetes', y='Prevalence of Diabetes', x='Year')
ggplot(pop, aes(x=year, y=p_hibpe_all)) +
        geom_line(col='black', size=0.3) +
        geom_line(data=diabe10, size=0.3, col='blue') +
        geom_line(data=diabe50, size=0.3, col='red') +
        geom_line(data=diabe100, size=0.3, col='dark green') +
        labs(title='Prevalence of Hypertension', y='Prevalence of Hypertension', x='Year')
ggplot(pop, aes(x=year, y=p_stroke_all)) +
        geom_line(col='black', size=0.3) +
        geom_line(data=diabe10, size=0.3, col='blue') +
        geom_line(data=diabe50, size=0.3, col='red') +
        geom_line(data=diabe100, size=0.3, col='dark green') +
        labs(title='Prevalence of Stroke', y='Prevalence of Stroke', x='Year')
ggplot(pop, aes(x=year, y=p_cancre_all)) +
        geom_line(col='black', size=0.3) +
        geom_line(data=diabe10, size=0.3, col='blue') +
        geom_line(data=diabe50, size=0.3, col='red') +
        geom_line(data=diabe100, size=0.3, col='dark green') +
        labs(title='Prevalence of Cancer', y='Prevalence of Cancer', x='Year')


```

